/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Doctor;
import Clases.DoctorsOffice;
import Clases.Hospital;
import DAO.DAOConsultorio;
import DAO.DAODoctor;
import DAO.DAOHospital;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author pamel
 */
public class Alta_consultorios extends javax.swing.JFrame {
  DoctorsOffice doffice;
    /**
     * Creates new form Alta_consultorios
     */
    public Alta_consultorios() throws SQLException, ClassNotFoundException {
        initComponents();
         this.setLocationRelativeTo(null);
         if(Baja_consultorio.modif==1)
         {
               loadcmbHospital();
         loadcmbDoctores();
             loadDoctorsOfficedata();
             jButton1.setText("Guardar cambios");
             
         }else
         {
             jButton1.setText("Crear");
         loadcmbHospital();
         loadcmbDoctores();
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_regresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFloor = new javax.swing.JTextField();
        txtMRent = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jcmbHospital = new javax.swing.JComboBox<>();
        jcmDoctor = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtPago = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_regresar.setText("Regresar");
        btn_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Número de piso: ");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Renta mensual:");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jcmDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmDoctorActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("Último pago:");
        jLabel4.setEnabled(false);

        txtPago.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcmbHospital, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcmDoctor, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 129, Short.MAX_VALUE)
                                .addComponent(btn_regresar))
                            .addComponent(txtFloor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtMRent)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPago, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_regresar)
                .addGap(35, 35, 35)
                .addComponent(jcmbHospital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jcmDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtFloor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMRent, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarActionPerformed
       Baja_consultorio.modif=0;
        Menu_Clinica obj = new Menu_Clinica();
      obj.setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_btn_regresarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(txtFloor.getText().matches("") || txtMRent.getText().matches("") || 
                jcmbHospital.getSelectedIndex()==0 || jcmDoctor.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(rootPane, "Por favor ingrese todos los campos");
        }else
        {
           if(Baja_consultorio.modif==0)
           {
            DoctorsOffice doctorsOffice=new DoctorsOffice();
            
            Hospital h=new Hospital();
            Doctor d=new Doctor();
            h=(Hospital)jcmbHospital.getSelectedItem();
            d=(Doctor)jcmDoctor.getSelectedItem();
            doctorsOffice.setFloor(Integer.parseInt(txtFloor.getText()));
            doctorsOffice.setMonthlyRent(Float.parseFloat(txtMRent.getText()));
            doctorsOffice.setIdhospital(h.getIdhospital());
            doctorsOffice.setDoctorID(d.getId());
            
            try {
                DAOConsultorio daoconsultorio=new DAOConsultorio();
              if(  daoconsultorio.saveConsultorio(doctorsOffice))
              {
                  JOptionPane.showMessageDialog(rootPane, "Consultorio agregado");
              }
              else
              {
                JOptionPane.showMessageDialog(rootPane, "Ocurrió un error");
              }
            } catch (SQLException ex) {
                Logger.getLogger(Alta_consultorios.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Alta_consultorios.class.getName()).log(Level.SEVERE, null, ex);
            }
           }else
           {
               try {
                   cargardatos();
                   DAOConsultorio daoconsultorio=new DAOConsultorio();
                   if(daoconsultorio.UpdateDoctorsOffice(doffice))
                   {
                       JOptionPane.showMessageDialog(rootPane, "Consultorio modificado");
                       loadDoctorsOfficedata();
                   }else
                   {
                        JOptionPane.showMessageDialog(rootPane, "Ocurrió un error");
                   }
                   
               } catch (SQLException ex) {
                   Logger.getLogger(Alta_consultorios.class.getName()).log(Level.SEVERE, null, ex);
               } catch (ClassNotFoundException ex) {
                   Logger.getLogger(Alta_consultorios.class.getName()).log(Level.SEVERE, null, ex);
               }
               
               
           }
            
            
            
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jcmDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmDoctorActionPerformed

   public void cargardatos()
   {
        Hospital h=new Hospital();
            Doctor d=new Doctor();
            h=(Hospital)jcmbHospital.getSelectedItem();
            d=(Doctor)jcmDoctor.getSelectedItem();
            doffice.setFloor(Integer.parseInt(txtFloor.getText()));
            doffice.setMonthlyRent(Float.parseFloat(txtMRent.getText()));
            doffice.setIdhospital(h.getIdhospital());
            doffice.setDoctorID(d.getId());
            doffice.setLastPayment(Float.parseFloat(txtPago.getText()));
   }
    public void loadDoctorsOfficedata() throws SQLException, ClassNotFoundException
    {
        DAOConsultorio daoconsultorio=new DAOConsultorio();
      
     doffice=daoconsultorio.getDoctorsOffice( Baja_consultorio.idconsultorio);
        jcmbHospital.setSelectedIndex(doffice.getIdhospital()-1);
        jcmDoctor.setSelectedIndex(Integer.parseInt(doffice.getDoctorID()));
        txtFloor.setText(doffice.getFloor().toString());
        txtMRent.setText(doffice.getMonthlyRent().toString());
        txtPago.setEnabled(true);
        jLabel4.setEnabled(true);
        txtPago.setText(doffice.getLastPayment().toString());
        
    }
    
    public void loadcmbDoctores() throws SQLException, ClassNotFoundException
    {
        DAODoctor daodoctor=new DAODoctor();
        Doctor d=new Doctor();
        DefaultComboBoxModel mode = new DefaultComboBoxModel();
          
            mode.removeAllElements();
            d.setId("0");
            d.setFirstname("Seleccione un doctor");
            d.setLastname(" ");
            mode.addElement(d);
            for(Doctor doctor:daodoctor.loaddoctors())
            {
                mode.addElement(doctor);
            }
            jcmDoctor.setModel(mode);
   
        
    }
    public void loadcmbHospital() throws SQLException, ClassNotFoundException
    {
        DAOHospital dAOHospital=new DAOHospital();
        Hospital h=new Hospital();
         DefaultComboBoxModel mode = new DefaultComboBoxModel();
          
            mode.removeAllElements();
         h.setIdhospital(0);
          h.setName("Seleccione un hospital");
           
            mode.addElement(h);
            for (Hospital hospital : dAOHospital.loadhospital()) {
                mode.addElement(hospital);
            }
            jcmbHospital.setModel(mode);
           
        
        
    }
    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_regresar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox<String> jcmDoctor;
    private javax.swing.JComboBox<String> jcmbHospital;
    private javax.swing.JTextField txtFloor;
    private javax.swing.JTextField txtMRent;
    private javax.swing.JFormattedTextField txtPago;
    // End of variables declaration//GEN-END:variables
}
