/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;
import Clases.Usuario;
import DAO.Login;
import java.applet.AudioClip;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author pamel
 */
public class Interface extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public Interface() {
        initComponents();
 
        this.setLocationRelativeTo(null);
    }
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/surgeon256_24934.png"));
        return retValue;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nombredeusuario = new javax.swing.JLabel();
        Contraseña = new javax.swing.JLabel();
        Texto_usuario = new javax.swing.JTextField();
        Icono = new javax.swing.JLabel();
        Texto_contraseña = new javax.swing.JPasswordField();
        Button1 = new javax.swing.JButton();
        Iniciar_Sesion = new javax.swing.JButton();
        Font = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nombredeusuario.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Nombredeusuario.setForeground(new java.awt.Color(255, 255, 255));
        Nombredeusuario.setText("Usuario: ");
        getContentPane().add(Nombredeusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 120, -1));

        Contraseña.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Contraseña.setForeground(new java.awt.Color(255, 255, 255));
        Contraseña.setText("Contraseña:");
        getContentPane().add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 130, -1));

        Texto_usuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Texto_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Texto_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(Texto_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 280, -1));

        Icono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/surgeon256_24934.png"))); // NOI18N
        getContentPane().add(Icono, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, -50, 270, 420));

        Texto_contraseña.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        getContentPane().add(Texto_contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 280, -1));

        Button1.setBackground(new java.awt.Color(204, 204, 204));
        Button1.setFont(new java.awt.Font("Sylfaen", 1, 14)); // NOI18N
        Button1.setForeground(new java.awt.Color(0, 0, 102));
        Button1.setText("x");
        Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button1ActionPerformed(evt);
            }
        });
        getContentPane().add(Button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 10, -1, 20));

        Iniciar_Sesion.setBackground(new java.awt.Color(0, 0, 102));
        Iniciar_Sesion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Iniciar_Sesion.setForeground(new java.awt.Color(255, 255, 255));
        Iniciar_Sesion.setText("Ingresar");
        Iniciar_Sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Iniciar_SesionMouseClicked(evt);
            }
        });
        Iniciar_Sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Iniciar_SesionActionPerformed(evt);
            }
        });
        Iniciar_Sesion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                Iniciar_SesionKeyReleased(evt);
            }
        });
        getContentPane().add(Iniciar_Sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 90, 30));

        Font.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/white bg.jpg"))); // NOI18N
        getContentPane().add(Font, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 874, 530));

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 460, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button1ActionPerformed
     System.exit(0);
    }//GEN-LAST:event_Button1ActionPerformed

    private void Iniciar_SesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Iniciar_SesionActionPerformed

if(this.Texto_usuario.getText().isEmpty() || this.Texto_contraseña.getPassword().equals(""))
{
    JOptionPane.showMessageDialog(rootPane, "Es necesario llenar los campos ", " ADVERTENCIA ",JOptionPane.WARNING_MESSAGE);
}
else
if(!this.Texto_usuario.getText().isEmpty()&& !this.Texto_contraseña.getPassword().equals(""))
{
   
    try {
        Login l=new Login();
        Usuario u=null;
        if(l.acceder(Texto_usuario.getText(),Texto_contraseña.getPassword())!=null)
        {
            Menu obj = new Menu();
            obj.setVisible(true);
            this.setVisible(false);
        }else
        {
            JOptionPane.showMessageDialog(rootPane, "Usuario y/o contraseña incorrecta");
        }
    } catch (SQLException ex) {
        Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
    }
        
        
    
  
}

    }//GEN-LAST:event_Iniciar_SesionActionPerformed

    private void Texto_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Texto_usuarioActionPerformed
       
    }//GEN-LAST:event_Texto_usuarioActionPerformed

    private void Iniciar_SesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Iniciar_SesionMouseClicked
        AudioClip sonido;
sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Ventanas/Grab.wav"));
sonido.play();
    }//GEN-LAST:event_Iniciar_SesionMouseClicked

    private void Iniciar_SesionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Iniciar_SesionKeyReleased
             if(this.Texto_usuario.getText().isEmpty())
            JOptionPane.showMessageDialog(rootPane, "Es necesario introducir tu nombre de usuario ", " ADVERTENCIA ",JOptionPane.WARNING_MESSAGE);
if(this.Texto_contraseña.getText().isEmpty())
            JOptionPane.showMessageDialog(rootPane, "Es necesario introducir tu contraseña ", " ADVERTENCIA ",JOptionPane.WARNING_MESSAGE);
else
if(!this.Texto_usuario.getText().isEmpty()&& !this.Texto_contraseña.getText().isEmpty())
{
    Menu obj = new Menu();
      obj.setVisible(true);
      this.setVisible(false);
}
        AudioClip sonido;
sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Ventanas/Grab.wav"));
sonido.play();
    }//GEN-LAST:event_Iniciar_SesionKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Interface().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button1;
    private javax.swing.JLabel Contraseña;
    private javax.swing.JLabel Font;
    private javax.swing.JLabel Icono;
    private javax.swing.JButton Iniciar_Sesion;
    private javax.swing.JLabel Nombredeusuario;
    private javax.swing.JPasswordField Texto_contraseña;
    private javax.swing.JTextField Texto_usuario;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
