/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Karen
 */
public class Menu_Clinica extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Clinica
     */
    public Menu_Clinica() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_bajaconsul = new javax.swing.JButton();
        btn_altaconsul = new javax.swing.JButton();
        btn_crearClinica = new javax.swing.JButton();
        btn_regresarmenu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 255));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btn_bajaconsul.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_bajaconsul.setText("Dar baja un consultorio");
        btn_bajaconsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bajaconsulActionPerformed(evt);
            }
        });

        btn_altaconsul.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_altaconsul.setText("Dar de alta consultorios");
        btn_altaconsul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_altaconsulActionPerformed(evt);
            }
        });

        btn_crearClinica.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btn_crearClinica.setText("Crear clínica");
        btn_crearClinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearClinicaActionPerformed(evt);
            }
        });

        btn_regresarmenu.setText("Regresar");
        btn_regresarmenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regresarmenuActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_regresarmenu)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_bajaconsul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_crearClinica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_altaconsul))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_regresarmenu)
                .addGap(90, 90, 90)
                .addComponent(btn_crearClinica)
                .addGap(18, 18, 18)
                .addComponent(btn_altaconsul)
                .addGap(18, 18, 18)
                .addComponent(btn_bajaconsul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_crearClinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearClinicaActionPerformed
        crear_clinica obj = new crear_clinica();
      obj.setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_btn_crearClinicaActionPerformed

    private void btn_regresarmenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regresarmenuActionPerformed
        Menu obj = new Menu();
      obj.setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_btn_regresarmenuActionPerformed

    private void btn_altaconsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_altaconsulActionPerformed
        try {
            Alta_consultorios obj = new Alta_consultorios();
            obj.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(Menu_Clinica.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Menu_Clinica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_altaconsulActionPerformed

    private void btn_bajaconsulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bajaconsulActionPerformed
        try {
            Baja_consultorio obj = new Baja_consultorio();
            obj.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(Menu_Clinica.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Menu_Clinica.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_bajaconsulActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_altaconsul;
    private javax.swing.JButton btn_bajaconsul;
    private javax.swing.JButton btn_crearClinica;
    private javax.swing.JButton btn_regresarmenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
